In [1]:
import anndata as ad
import scanpy as sc
import numpy as np

fully_annotated is already scaled

In [2]:
scaled = sc.read_h5ad("/hdd/edward/the-project/results/discrete_cancer_stages_annotated.h5ad")
scaled

AnnData object with n_obs × n_vars = 122649 × 12850
    obs: 'sample_source', 'sample_ID', 'n_genes', 'n_genes_by_counts', 'total_counts', 'total_counts_mt', 'pct_counts_mt', 'leiden', 'cell_type', 'cell_cycle', 'Gender', 'Age', 'Shimada', 'INSS_stage', 'COG_risk_group', 'Distant_metastasis', 'NSE', 'LDH', 'MYCN-amp', 'Survival/Death', 'discrete_cancer_stage'
    var: 'mt', 'highly_variable', 'means', 'dispersions', 'dispersions_norm'
    uns: 'INSS_stage_colors', 'hvg', 'leiden', 'leiden_colors', 'leiden_sizes', 'log1p', 'neighbors', 'paga', 'pca', 'sample_ID_colors', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_umap'
    obsp: 'connectivities', 'distances'

In [3]:
# # consult to https://www.jianshu.com/p/4530d2955562
# scaled = sc.pp.scale(adata, copy=True)
# scaled  # scaled.var["mean", "std"] are added

AnnData object with n_obs × n_vars = 197850 × 12850
    obs: 'n_genes', 'n_genes_by_counts', 'total_counts', 'total_counts_mt', 'pct_counts_mt'
    var: 'n_cells', 'mt', 'n_cells_by_counts', 'mean_counts', 'pct_dropout_by_counts', 'total_counts', 'mean', 'std'

In [3]:
scaled.X

array([[-0.32697654, -0.49746022, -0.21847789, ..., -0.13813582,
         0.88954717, -0.1124419 ],
       [-0.32697654, -0.49746022, -0.21847789, ..., -0.13813582,
         0.7077023 , -0.1124419 ],
       [-0.32697654, -0.49746022,  5.1801367 , ..., -0.13813582,
         0.8751176 , -0.1124419 ],
       ...,
       [-0.32697654, -0.49746022, -0.21847789, ..., -0.13813582,
        -0.30766338, -0.1124419 ],
       [-0.32697654,  2.3153143 , -0.21847789, ..., -0.13813582,
         0.77141887, -0.1124419 ],
       [-0.32697654, -0.49746022, -0.21847789, ..., -0.13813582,
         0.8525672 , -0.1124419 ]], dtype=float32)

In [5]:
scaled.var

              mt  highly_variable     means  dispersions  dispersions_norm
Symbol
TSPAN6     False             True  0.520015     2.321722          0.458247
DPM1       False            False  0.885202     2.248470         -0.140027
SCYL3      False            False  0.242544     2.206272         -0.280784
C1orf112   False            False  0.187474     2.251486         -0.110174
FGR        False            False  0.009380     2.077023         -0.768486
...          ...              ...       ...          ...               ...
LINC01481  False            False  0.333529     1.598487         -2.574180
CYB561D2   False            False  0.424463     2.151259         -0.638191
CCDC7      False            False  0.085229     2.047633         -0.879387
RGS5       False             True  3.145957     3.762795          1.643996
MATR3      False            False  0.044241     1.533989         -2.817555

[12850 rows x 5 columns]

In [4]:
scaled.var

,n_cells,mt,n_cells_by_counts,mean_counts,pct_dropout_by_counts,total_counts,highly_variable,means,dispersions,dispersions_norm,mean,std
Symbol,,,,,,,,,,,,
TSPAN6,22827,False,22827,0.139813,88.754729,28381.0,True,0.522114,2.311881,0.386675,0.195619,0.594493
DPM1,41703,False,41703,0.255813,79.455841,51928.0,False,0.887971,2.235595,-0.147037,0.405976,0.808990
SCYL3,8124,False,8124,0.042524,95.997872,8632.0,False,0.242524,2.192319,-0.250465,0.086309,0.392228
C1orf112,6162,False,6162,0.032287,96.964412,6554.0,False,0.187566,2.242408,-0.066227,0.064737,0.339810
FGR,3049,False,3049,0.020690,98.497970,4200.0,False,0.012016,2.010060,-0.920850,0.003903,0.085170
...,...,...,...,...,...,...,...,...,...,...,...,...
LINC01481,17206,False,17206,0.051539,91.523804,10462.0,False,0.332432,1.590062,-2.465693,0.151870,0.470074
CYB561D2,22444,False,22444,0.098090,88.943407,19911.5,False,0.425491,2.139109,-0.594490,0.180985,0.527789
CCDC7,3626,False,3626,0.014993,98.213723,3043.5,False,0.085833,2.028026,-0.854770,0.032157,0.229995
RGS5,78674,False,78674,2.696656,61.242808,547399.5,True,3.142079,3.754977,1.682952,1.788769,1.850659
MATR3,2601,False,2601,0.007311,98.718669,1484.0,False,0.044489,1.523003,-2.712351,0.018905,0.166458

In [20]:
# print(adata.obsm["X_pca"].shape)  # there're 50 PC dimensions used, each cell has a 50-D coordinate
# adata.obsm["X_pca"]

AxisArrays with keys:

smoothing starts

<!-- incorporating annotations of the coordinates in the 50-pc space -->

In [7]:
# ldata = sc.read_h5ad("/hdd/edward/the-project/results/leiden.h5ad")
# ldata

AnnData object with n_obs × n_vars = 197850 × 2289
    obs: 'n_genes', 'n_genes_by_counts', 'total_counts', 'total_counts_mt', 'pct_counts_mt', 'leiden'
    var: 'n_cells', 'mt', 'n_cells_by_counts', 'mean_counts', 'pct_dropout_by_counts', 'total_counts', 'highly_variable', 'means', 'dispersions', 'dispersions_norm', 'mean', 'std'
    uns: 'hvg', 'leiden', 'leiden_colors', 'leiden_sizes', 'log1p', 'neighbors', 'paga', 'pca', 'umap'
    obsm: 'X_pca', 'X_umap'
    varm: 'PCs'
    obsp: 'connectivities', 'distances'

In [9]:
# scaled.obsm = ldata.obsm
# scaled

AnnData object with n_obs × n_vars = 197850 × 12850
    obs: 'n_genes', 'n_genes_by_counts', 'total_counts', 'total_counts_mt', 'pct_counts_mt'
    var: 'n_cells', 'mt', 'n_cells_by_counts', 'mean_counts', 'pct_dropout_by_counts', 'total_counts', 'mean', 'std'
    obsm: 'X_pca', 'X_umap'

In [7]:
scaled

AnnData object with n_obs × n_vars = 122649 × 12850
    obs: 'sample_source', 'sample_ID', 'n_genes', 'n_genes_by_counts', 'total_counts', 'total_counts_mt', 'pct_counts_mt', 'leiden', 'cell_type', 'cell_cycle', 'Gender', 'Age', 'Shimada', 'INSS_stage', 'COG_risk_group', 'Distant_metastasis', 'NSE', 'LDH', 'MYCN-amp', 'Survival/Death', 'discrete_cancer_stage'
    var: 'mt', 'highly_variable', 'means', 'dispersions', 'dispersions_norm'
    uns: 'INSS_stage_colors', 'hvg', 'leiden', 'leiden_colors', 'leiden_sizes', 'log1p', 'neighbors', 'paga', 'pca', 'sample_ID_colors', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_umap'
    obsp: 'connectivities', 'distances'

In [6]:
# pca before batch correction
scaled.obsm["X_pca"]

array([[-6.3935986e+00,  6.9654164e+00,  1.4936496e+00, ...,
        -6.4403808e-01,  1.5272384e+00,  1.5963532e+00],
       [-7.9736938e+00,  4.9232483e+00,  3.6722703e+00, ...,
        -1.6151998e+00,  1.2791624e+00,  8.9897937e-01],
       [-7.4366136e+00,  4.9374585e+00,  3.2423592e+00, ...,
         4.6688661e-01,  9.0752792e-01, -5.8634090e-01],
       ...,
       [-4.7889333e+00,  5.2143264e+00,  7.7207899e+00, ...,
        -6.4662385e-01, -2.3048277e-01, -5.6052811e-02],
       [ 1.6512732e+01,  6.1217980e+00,  1.2373014e+01, ...,
         6.4498055e-01,  1.4967186e+00, -1.2282786e+00],
       [-4.8927960e+00,  8.2306471e+00,  6.0153890e+00, ...,
        -4.6624970e-03, -2.0797164e+00,  4.8483500e-01]], dtype=float32)

In [8]:
# batch corrected pca values
scaled.obsm["X_pca_harmony"]

array([[-3.5894167 ,  4.883723  ,  0.30742854, ..., -0.8101141 ,
         1.4416783 ,  1.4392995 ],
       [-5.5514107 ,  2.7589812 ,  2.6047475 , ..., -1.336814  ,
         1.3128057 ,  0.783333  ],
       [-2.2556496 ,  1.2103211 ,  3.183937  , ...,  0.5067268 ,
         1.3494372 , -0.68202454],
       ...,
       [-0.66662085, -0.08070537,  6.1975126 , ..., -0.5275606 ,
        -0.26376787, -0.05982092],
       [16.261616  ,  2.307541  ,  7.643749  , ...,  0.88249785,
         1.5777321 , -1.4566531 ],
       [-1.0678113 ,  3.1713524 ,  4.2754807 , ...,  0.12321155,
        -2.1026754 ,  0.43668562]], dtype=float32)

In [10]:
scaled.obsm["X_pca"].shape

(122649, 50)

In [7]:
# save scaled data
# identical to cell_type_classified.h5ad
scaled.write("/hdd/edward/the-project/results/pipeline/scaled.h5ad")

start smoothing with knn algorithm

creating smoothed data by using adata as a template

In [8]:
import scanpy as sc # if necessary
scaled = sc.read_h5ad("/hdd/edward/the-project/results/pipeline/scaled.h5ad")
scaled

AnnData object with n_obs × n_vars = 126356 × 12850
    obs: 'sample_source', 'patient_ID', 'n_genes', 'n_genes_by_counts', 'total_counts', 'total_counts_mt', 'pct_counts_mt', 'cell_type', 'Gender', 'Age', 'Shimada', 'INSS_stage', 'COG_risk_group', 'Distant_metastasis', 'NSE', 'LDH', 'MYCN-amp', 'Survival/Death', 'leiden', 'sc_cancer_stage'
    var: 'n_cells', 'mt', 'n_cells_by_counts', 'mean_counts', 'pct_dropout_by_counts', 'total_counts', 'highly_variable', 'means', 'dispersions', 'dispersions_norm', 'mean', 'std'
    uns: 'INSS_stage_colors', 'hvg', 'leiden', 'leiden_colors', 'leiden_sizes', 'log1p', 'neighbors', 'paga', 'patient_ID_colors', 'pca', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_umap'
    obsp: 'connectivities', 'distances'

In [9]:
smoothed = scaled.copy()
smoothed

AnnData object with n_obs × n_vars = 126356 × 12850
    obs: 'sample_source', 'patient_ID', 'n_genes', 'n_genes_by_counts', 'total_counts', 'total_counts_mt', 'pct_counts_mt', 'cell_type', 'Gender', 'Age', 'Shimada', 'INSS_stage', 'COG_risk_group', 'Distant_metastasis', 'NSE', 'LDH', 'MYCN-amp', 'Survival/Death', 'leiden', 'sc_cancer_stage'
    var: 'n_cells', 'mt', 'n_cells_by_counts', 'mean_counts', 'pct_dropout_by_counts', 'total_counts', 'highly_variable', 'means', 'dispersions', 'dispersions_norm', 'mean', 'std'
    uns: 'INSS_stage_colors', 'hvg', 'leiden', 'leiden_colors', 'leiden_sizes', 'log1p', 'neighbors', 'paga', 'patient_ID_colors', 'pca', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_umap'
    obsp: 'connectivities', 'distances'

modify the content of "smoothed" by actually smoothing

In [10]:
print(scaled.obsm["X_pca"].shape)
print(scaled.obsm["X_pca"])
# for point in adata.obsm["X_pca"]:

(126356, 50)
[[-6.7415056e+00  6.4965415e+00  1.9207556e+00 ... -1.3622922e+00
   1.2431202e+00  3.7634295e-01]
 [-8.0773211e+00  4.1552935e+00  3.0127323e+00 ... -7.8211361e-01
  -1.1285811e-03  4.2589998e-01]
 [-8.8310966e+00 -1.2154772e-01  2.0101762e+00 ...  4.9420315e-01
   2.0401460e-01 -9.3653250e-01]
 ...
 [-6.4865065e-01  7.3470569e+00  2.5953434e+01 ... -8.8667166e-01
  -6.3699573e-01  8.5873055e-01]
 [ 1.6230570e+01  8.5600567e+00  1.2135562e+01 ... -1.7373726e+00
  -1.3033794e+00 -9.7319907e-01]
 [-5.0411134e+00  8.4861097e+00  8.9913826e+00 ...  3.2708304e+00
  -1.7003365e+00 -2.3023944e+00]]

let's write a function to smoothing

In [59]:
# def smooth(nrows_output, knn):  # nrows_output = len(smoothed.X)
#     from sklearn.neighbors import KDTree
#     X = scaled.obsm["X_pca"]
#     tree = KDTree(X)
#     for i in range(nrows_output):
#         distances, indices = tree.query(X[nrows_output:nrows_output+1], knn+1)
#         print(indices)
#         m = np.mean([scaled.X[i] for i in indices[0]], axis=0)
#         smoothed.X[i] = m

In [11]:
from sklearn.neighbors import KDTree
X = scaled.obsm["X_pca"]
print(X)

[[-6.7415056e+00  6.4965415e+00  1.9207556e+00 ... -1.3622922e+00
   1.2431202e+00  3.7634295e-01]
 [-8.0773211e+00  4.1552935e+00  3.0127323e+00 ... -7.8211361e-01
  -1.1285811e-03  4.2589998e-01]
 [-8.8310966e+00 -1.2154772e-01  2.0101762e+00 ...  4.9420315e-01
   2.0401460e-01 -9.3653250e-01]
 ...
 [-6.4865065e-01  7.3470569e+00  2.5953434e+01 ... -8.8667166e-01
  -6.3699573e-01  8.5873055e-01]
 [ 1.6230570e+01  8.5600567e+00  1.2135562e+01 ... -1.7373726e+00
  -1.3033794e+00 -9.7319907e-01]
 [-5.0411134e+00  8.4861097e+00  8.9913826e+00 ...  3.2708304e+00
  -1.7003365e+00 -2.3023944e+00]]

In [12]:
K = 31  # number of nearest neighbors + 1
tree = KDTree(X, leaf_size=40, metric='euclidean')
# For finding K neighbors of P1 with shape (1, 3)
# distances, indices = tree.query(X[:1], K)  # slice the data by [a:b] to retain the array's dimension, because it only allows 2D input
indices = tree.query(X, K, return_distance=False)
print(indices)
# print(distances)

[[     0   5910   4265 ...   1865   3978   1037]
 [     1   2028   4901 ...   4096   5990    456]
 [     2   3663   3948 ...   2325   4774    380]
 ...
 [126353 126242 126002 ... 125469  51337 125916]
 [126354 125479 126167 ... 125428 126162 125624]
 [126355 125229 125515 ... 125540 125863 125805]]

let's save the knn indices information into a .npy file

In [13]:
np.save("/hdd/edward/the-project/results/pipeline/knn_indices.npy", indices)

let's substitute unsmoothed data with smoothed ones

In [14]:
for i in range(len(scaled.X)):
    smoothed.X[i] = np.mean([scaled.X[j] for j in indices[i]], axis=0)

In [15]:
smoothed.X

array([[-0.15482108, -0.18579069,  0.04031989, ..., -0.13981676,
         0.73953146, -0.00616651],
       [-0.02305921, -0.2563505 ,  0.05916706, ..., -0.13981676,
         0.7896203 ,  0.15851392],
       [ 0.08974789, -0.20172995, -0.05014118, ..., -0.13981676,
         0.7132579 , -0.11357003],
       ...,
       [-0.20971888,  0.40749413,  0.0819965 , ..., -0.01252127,
         0.37049103,  0.01715944],
       [-0.0828659 ,  1.0496024 ,  0.26523763, ..., -0.0616001 ,
         0.7919027 ,  0.37795335],
       [-0.1847254 ,  0.53514564,  0.0806121 , ..., -0.13981676,
         0.75468475,  0.19202395]], dtype=float32)

In [16]:
smoothed

AnnData object with n_obs × n_vars = 126356 × 12850
    obs: 'sample_source', 'patient_ID', 'n_genes', 'n_genes_by_counts', 'total_counts', 'total_counts_mt', 'pct_counts_mt', 'cell_type', 'Gender', 'Age', 'Shimada', 'INSS_stage', 'COG_risk_group', 'Distant_metastasis', 'NSE', 'LDH', 'MYCN-amp', 'Survival/Death', 'leiden', 'sc_cancer_stage'
    var: 'n_cells', 'mt', 'n_cells_by_counts', 'mean_counts', 'pct_dropout_by_counts', 'total_counts', 'highly_variable', 'means', 'dispersions', 'dispersions_norm', 'mean', 'std'
    uns: 'INSS_stage_colors', 'hvg', 'leiden', 'leiden_colors', 'leiden_sizes', 'log1p', 'neighbors', 'paga', 'patient_ID_colors', 'pca', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_umap'
    obsp: 'connectivities', 'distances'

In [17]:
smoothed.write("/hdd/edward/the-project/results/pipeline/smoothed.h5ad")

In [11]:
# m = np.mean([scaled.X[i] for i in indices[0]], axis=0)
# print(m)

[-0.09184327 -0.11308052  0.10155749 ... -0.12689394  0.6373073
 -0.10948849]

In [38]:
## this method works too

# a = sum([scaled.X[i] for i in indices[0]])/31 # this method works too
# print(a)

[-0.09184327 -0.11308052  0.10155749 ... -0.12689394  0.6373073
 -0.10948849]