In [1]:
import xmltodict
import pandas as pd
import numpy as np

In [2]:
file = open("full_database.xml")
xml_string = file.read()
file.close()

In [3]:
python_dict = xmltodict.parse(xml_string)

In [4]:
# python_dict['drugbank'].keys()

In [5]:
# np.shape(python_dict['drugbank']['drug'])

In [6]:
data = pd.DataFrame.from_dict(python_dict['drugbank']['drug'])
data

,@type,@created,@updated,drugbank-id,name,description,cas-number,unii,state,groups,...,snp-adverse-drug-reactions,targets,enzymes,carriers,transporters,fda-label,msds,average-mass,monoisotopic-mass,calculated-properties
0,biotech,2005-06-13,2024-01-02,"[{'@primary': 'true', '#text': 'DB00001'}, BTD...",Lepirudin,Lepirudin is a recombinant hirudin formed by 6...,138068-37-8,Y43GF64R34,solid,"{'group': ['approved', 'withdrawn']}",...,None,"{'target': {'@position': '1', 'id': 'BE0000048...",None,None,None,NaN,NaN,NaN,NaN,NaN
1,biotech,2005-06-13,2024-01-02,"[{'@primary': 'true', '#text': 'DB00002'}, BTD...",Cetuximab,Cetuximab is a recombinant chimeric human/mous...,205923-56-4,PQX0D8J21J,liquid,{'group': 'approved'},...,None,"{'target': [{'@position': '1', 'id': 'BE000076...",None,None,None,//s3-us-west-2.amazonaws.com/drugbank/fda_labe...,//s3-us-west-2.amazonaws.com/drugbank/msds/DB0...,NaN,NaN,NaN
2,biotech,2005-06-13,2024-01-02,"[{'@primary': 'true', '#text': 'DB00003'}, BTD...",Dornase alfa,Dornase alfa is a biosynthetic form of human d...,143831-71-4,953A26OA1Y,liquid,{'group': 'approved'},...,None,"{'target': {'@position': '1', 'id': 'BE0004796...",None,None,None,//s3-us-west-2.amazonaws.com/drugbank/fda_labe...,//s3-us-west-2.amazonaws.com/drugbank/msds/DB0...,NaN,NaN,NaN
3,biotech,2005-06-13,2024-01-02,"[{'@primary': 'true', '#text': 'DB00004'}, BTD...",Denileukin diftitox,A recombinant DNA-derived cytotoxic protein co...,173146-27-5,25E79B5CTM,liquid,"{'group': ['approved', 'investigational']}",...,None,"{'target': [{'@position': '1', 'id': 'BE000065...",None,None,None,//s3-us-west-2.amazonaws.com/drugbank/fda_labe...,NaN,NaN,NaN,NaN
4,biotech,2005-06-13,2023-10-20,"[{'@primary': 'true', '#text': 'DB00005'}, BTD...",Etanercept,Dimeric fusion protein consisting of the extra...,185243-69-0,OP401G7OJC,liquid,"{'group': ['approved', 'investigational']}",...,None,"{'target': [{'@position': '1', 'id': 'BE000070...",None,None,None,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16570,small molecule,2023-12-08,2023-12-09,"{'@primary': 'true', '#text': 'DB18707'}",AVL-3288,None,917837-54-8,VA80VAX4WF,NaN,{'group': 'investigational'},...,None,None,None,None,None,NaN,NaN,388.25,387.0541321,"{'property': [{'kind': 'logP', 'value': '4.1',..."
16571,small molecule,2023-12-09,2023-12-09,"{'@primary': 'true', '#text': 'DB18708'}",Alogabat,None,2230009-48-8,0HPA4GK3UH,NaN,{'group': 'investigational'},...,None,None,None,None,None,NaN,NaN,409.446,409.175004241,"{'property': [{'kind': 'logP', 'value': '0.87'..."
16572,small molecule,2023-12-11,2023-12-12,"{'@primary': 'true', '#text': 'DB18709'}",Ropsacitinib,None,2127109-84-4,HY5SOV7O0Q,NaN,{'group': 'investigational'},...,None,None,None,None,None,NaN,NaN,383.419,383.160691583,"{'property': [{'kind': 'logP', 'value': '1.09'..."
16573,biotech,2023-12-11,2023-12-19,"{'@primary': 'true', '#text': 'DB18710'}",ABBV-706,ABBV-706 is an antibody-drug conjugate that is...,None,None,NaN,{'group': 'investigational'},...,None,None,None,None,None,NaN,NaN,NaN,NaN,NaN
16574,small molecule,2023-12-21,2023-12-22,"{'@primary': 'true', '#text': 'DB18711'}",taletrectinib,None,1505515-69-4,6KLL51GNBG,NaN,{'group': 'investigational'},...,None,None,None,None,None,NaN,NaN,551.619,551.254397378,"{'property': [{'kind': 'logP', 'value': '4.03'..."

In [7]:
# data['drugbank-id'][0]

In [8]:
# data['drugbank-id'][15560]

In [9]:
id = pd.DataFrame(columns=['id'], index=data.index)
id

        id
0      NaN
1      NaN
2      NaN
3      NaN
4      NaN
...    ...
16570  NaN
16571  NaN
16572  NaN
16573  NaN
16574  NaN

[16575 rows x 1 columns]

In [10]:
for i in range(16575):
    if isinstance(data['drugbank-id'][i], list):
        id.loc[i] = data['drugbank-id'][i][0]['#text']
    else:
        id.loc[i] = data['drugbank-id'][i]['#text']

In [11]:
### bind to the original dataframe
data = pd.concat([data, id], axis = 1)
data

,@type,@created,@updated,drugbank-id,name,description,cas-number,unii,state,groups,...,targets,enzymes,carriers,transporters,fda-label,msds,average-mass,monoisotopic-mass,calculated-properties,id
0,biotech,2005-06-13,2024-01-02,"[{'@primary': 'true', '#text': 'DB00001'}, BTD...",Lepirudin,Lepirudin is a recombinant hirudin formed by 6...,138068-37-8,Y43GF64R34,solid,"{'group': ['approved', 'withdrawn']}",...,"{'target': {'@position': '1', 'id': 'BE0000048...",None,None,None,NaN,NaN,NaN,NaN,NaN,DB00001
1,biotech,2005-06-13,2024-01-02,"[{'@primary': 'true', '#text': 'DB00002'}, BTD...",Cetuximab,Cetuximab is a recombinant chimeric human/mous...,205923-56-4,PQX0D8J21J,liquid,{'group': 'approved'},...,"{'target': [{'@position': '1', 'id': 'BE000076...",None,None,None,//s3-us-west-2.amazonaws.com/drugbank/fda_labe...,//s3-us-west-2.amazonaws.com/drugbank/msds/DB0...,NaN,NaN,NaN,DB00002
2,biotech,2005-06-13,2024-01-02,"[{'@primary': 'true', '#text': 'DB00003'}, BTD...",Dornase alfa,Dornase alfa is a biosynthetic form of human d...,143831-71-4,953A26OA1Y,liquid,{'group': 'approved'},...,"{'target': {'@position': '1', 'id': 'BE0004796...",None,None,None,//s3-us-west-2.amazonaws.com/drugbank/fda_labe...,//s3-us-west-2.amazonaws.com/drugbank/msds/DB0...,NaN,NaN,NaN,DB00003
3,biotech,2005-06-13,2024-01-02,"[{'@primary': 'true', '#text': 'DB00004'}, BTD...",Denileukin diftitox,A recombinant DNA-derived cytotoxic protein co...,173146-27-5,25E79B5CTM,liquid,"{'group': ['approved', 'investigational']}",...,"{'target': [{'@position': '1', 'id': 'BE000065...",None,None,None,//s3-us-west-2.amazonaws.com/drugbank/fda_labe...,NaN,NaN,NaN,NaN,DB00004
4,biotech,2005-06-13,2023-10-20,"[{'@primary': 'true', '#text': 'DB00005'}, BTD...",Etanercept,Dimeric fusion protein consisting of the extra...,185243-69-0,OP401G7OJC,liquid,"{'group': ['approved', 'investigational']}",...,"{'target': [{'@position': '1', 'id': 'BE000070...",None,None,None,NaN,NaN,NaN,NaN,NaN,DB00005
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16570,small molecule,2023-12-08,2023-12-09,"{'@primary': 'true', '#text': 'DB18707'}",AVL-3288,None,917837-54-8,VA80VAX4WF,NaN,{'group': 'investigational'},...,None,None,None,None,NaN,NaN,388.25,387.0541321,"{'property': [{'kind': 'logP', 'value': '4.1',...",DB18707
16571,small molecule,2023-12-09,2023-12-09,"{'@primary': 'true', '#text': 'DB18708'}",Alogabat,None,2230009-48-8,0HPA4GK3UH,NaN,{'group': 'investigational'},...,None,None,None,None,NaN,NaN,409.446,409.175004241,"{'property': [{'kind': 'logP', 'value': '0.87'...",DB18708
16572,small molecule,2023-12-11,2023-12-12,"{'@primary': 'true', '#text': 'DB18709'}",Ropsacitinib,None,2127109-84-4,HY5SOV7O0Q,NaN,{'group': 'investigational'},...,None,None,None,None,NaN,NaN,383.419,383.160691583,"{'property': [{'kind': 'logP', 'value': '1.09'...",DB18709
16573,biotech,2023-12-11,2023-12-19,"{'@primary': 'true', '#text': 'DB18710'}",ABBV-706,ABBV-706 is an antibody-drug conjugate that is...,None,None,NaN,{'group': 'investigational'},...,None,None,None,None,NaN,NaN,NaN,NaN,NaN,DB18710
16574,small molecule,2023-12-21,2023-12-22,"{'@primary': 'true', '#text': 'DB18711'}",taletrectinib,None,1505515-69-4,6KLL51GNBG,NaN,{'group': 'investigational'},...,None,None,None,None,NaN,NaN,551.619,551.254397378,"{'property': [{'kind': 'logP', 'value': '4.03'...",DB18711

In [28]:
!pwd
%cd ../Reciprocal_nlog/
# %cd Cell/Nlog_nabslog/
!pwd

/home/jovyan/work/drug_screening/Cell/Nlog_reciprocal
/home/jovyan/work/drug_screening/Cell/Reciprocal_nlog
/home/jovyan/work/drug_screening/Cell/Reciprocal_nlog

In [30]:
I_4S_db = dict()
with open('I_to_4S_-1.96_drugs.txt') as f:
    for line in f.readlines():
        line = line.strip()
        id = line.split(',')[0]
        z_score = float(line.split(',')[1])
        I_4S_db[id] = z_score

I_to_4S = data[data['id'].isin(I_4S_db)].copy()
# Add the proximity_z column based on the mapping
I_to_4S['proximity_z'] = I_to_4S['id'].map(I_4S_db)
I_to_4S.sort_values(by='proximity_z', inplace=True)
I_to_4S.reset_index(drop=True, inplace=True)
I_to_4S.to_csv("I_to_4S.csv", na_rep='NULL')
I_to_4S

Empty DataFrame
Columns: [@type, @created, @updated, drugbank-id, name, description, cas-number, unii, state, groups, general-references, synthesis-reference, indication, pharmacodynamics, mechanism-of-action, toxicity, metabolism, absorption, half-life, protein-binding, route-of-elimination, volume-of-distribution, clearance, classification, salts, synonyms, products, international-brands, mixtures, packagers, manufacturers, prices, categories, affected-organisms, dosages, atc-codes, ahfs-codes, pdb-entries, patents, food-interactions, drug-interactions, sequences, experimental-properties, external-identifiers, external-links, pathways, reactions, snp-effects, snp-adverse-drug-reactions, targets, enzymes, carriers, transporters, fda-label, msds, average-mass, monoisotopic-mass, calculated-properties, id, proximity_z]
Index: []

[0 rows x 60 columns]

In [32]:
III_4S_db = dict()
with open('III_to_4S_-1.96_drugs.txt') as f:
    for line in f.readlines():
        line = line.strip()
        id = line.split(',')[0]
        z_score = float(line.split(',')[1])
        III_4S_db[id] = z_score
        
III_to_4S = data[data['id'].isin(III_4S_db)].copy()
# Add the proximity_z column based on the mapping
III_to_4S['proximity_z'] = III_to_4S['id'].map(III_4S_db)
III_to_4S.sort_values(by='proximity_z', inplace=True)
III_to_4S.reset_index(drop=True, inplace=True)
III_to_4S.to_csv("III_to_4S.csv", na_rep='NULL')
III_to_4S

,@type,@created,@updated,drugbank-id,name,description,cas-number,unii,state,groups,...,enzymes,carriers,transporters,fda-label,msds,average-mass,monoisotopic-mass,calculated-properties,id,proximity_z
0,small molecule,2005-06-13,2020-07-02,"[{'@primary': 'true', '#text': 'DB02494'}, EXP...",(S)-3-phenyllactic acid,None,20312-36-1,KW7SNV9X8B,solid,{'group': 'experimental'},...,None,None,None,NaN,NaN,166.1739,166.062994186,"{'property': [{'kind': 'logP', 'value': '0.84'...",DB02494,-3.931058
1,small molecule,2010-09-15,2020-06-12,"{'@primary': 'true', '#text': 'DB07374'}",Anisomycin,"Anisomycin (sometimes known as flagecidin), is...",22862-76-6,6C74YM2NGI,solid,{'group': 'experimental'},...,None,None,None,NaN,NaN,265.305,265.131408101,"{'property': [{'kind': 'logP', 'value': '0.97'...",DB07374,-3.907570
2,small molecule,2010-09-15,2021-02-21,"{'@primary': 'true', '#text': 'DB08437'}",Puromycin,Puromycin is an antibiotic that prevents bacte...,53-79-2,4A6ZS6Q2CL,solid,{'group': 'experimental'},...,None,None,None,NaN,NaN,471.5096,471.223017073,"{'property': [{'kind': 'logP', 'value': '-0.1'...",DB08437,-3.907570
3,small molecule,2005-06-13,2024-01-02,"[{'@primary': 'true', '#text': 'DB00720'}, APR...",Clodronic acid,Clodronic acid is a first generation bisphosph...,10596-23-3,0813BZ6866,solid,"{'group': ['approved', 'investigational', 'vet...",...,"{'enzyme': {'@position': '1', 'id': 'BE0000262...",None,None,NaN,//s3-us-west-2.amazonaws.com/drugbank/msds/DB0...,244.892,243.886016298,"{'property': [{'kind': 'logP', 'value': '0.16'...",DB00720,-3.551479
4,small molecule,2005-06-13,2020-06-12,"[{'@primary': 'true', '#text': 'DB03429'}, EXP...",Tetrastearoyl cardiolipin,None,None,None,solid,{'group': 'experimental'},...,None,None,None,NaN,NaN,1466.0585,1465.097426654,"{'property': [{'kind': 'logP', 'value': '8.97'...",DB03429,-2.610566
5,small molecule,2005-06-13,2020-06-12,"[{'@primary': 'true', '#text': 'DB01736'}, EXP...",[3-(Dodecanoylamino)Propyl](Hydroxy)Dimethylam...,None,None,I6KX160QTV,solid,{'group': 'experimental'},...,None,None,None,NaN,NaN,300.4799,300.277678406,"{'property': [{'kind': 'logP', 'value': '2.24'...",DB01736,-2.610566
6,small molecule,2005-06-13,2020-07-02,"[{'@primary': 'true', '#text': 'DB02426'}, EXP...",Carboxyatractyloside,None,33286-30-5,PH9ATM6F5U,solid,{'group': 'experimental'},...,None,None,None,NaN,NaN,786.816,786.20747067,"{'property': [{'kind': 'logP', 'value': '-0.38...",DB02426,-2.610566
7,small molecule,2005-06-13,2024-01-02,"[{'@primary': 'true', '#text': 'DB00390'}, APR...",Digoxin,Digoxin is one of the oldest cardiovascular me...,20830-75-5,73K4184T59,solid,{'group': 'approved'},...,"{'enzyme': {'@position': '1', 'id': 'BE0003537...",None,"{'transporter': [{'@position': '1', 'id': 'BE0...",NaN,//s3-us-west-2.amazonaws.com/drugbank/msds/DB0...,780.9385,780.429606756,"{'property': [{'kind': 'logP', 'value': '1.04'...",DB00390,-2.609656
8,small molecule,2005-06-13,2021-05-07,"[{'@primary': 'true', '#text': 'DB01078'}, APR...",Deslanoside,Deacetyllanatoside C. A cardiotonic glycoside ...,17598-65-1,YGY317RK75,solid,{'group': 'approved'},...,None,None,None,NaN,NaN,943.0791,942.482430186,"{'property': [{'kind': 'logP', 'value': '-0.49...",DB01078,-2.609656
9,small molecule,2005-06-13,2021-05-07,"[{'@primary': 'true', '#text': 'DB01092'}, APR...",Ouabain,A cardioactive glycoside consisting of rhamnos...,630-60-4,5ACL011P69,solid,{'group': 'approved'},...,None,None,"{'transporter': [{'@position': '1', 'id': 'BE0...",NaN,NaN,584.6525,584.283276872,"{'property': [{'kind': 'logP', 'value': '-1', ...",DB01092,-2.609656
10,small molecule,2005-06-13,2023-11-03,"[{'@primary': 'true', '#text': 'DB00511'}, APR...",Acetyldigitoxin,Cardioactive derivative of lanatoside A or of ...,1111-39-3,0ZV4Q4L2FU,solid,{'group': 'approved'},...,None,None,None,NaN,NaN,806.9757,806.44525682,"{'property': [{'kind': 'logP', 'value': '2.87'...",DB00511,-2.609656
11,small molecule,2005-06-13,2024-01-02,"[{'@primary': 'true', '#text': 'DB01158'}, APR...",Bretylium,Bretylium blocks the release of noradrenaline ...,59-41-6,RZR75EQ2KJ,solid,{'group': 'approved'},...,None,None,None,NaN,//s3-us-west-2.amazonaws.com/drugbank/msds/DB0...,243.163,242.054437196,"{'property': [{'kind': 'logP', 'value': '-1.4'...",DB01158,-2.609656
12,small molecule,2007-06-30,2024-01-02,"{'@primary': 'true', '#text': 'DB01345'}",Potassium cation,Potassium is the major cation (positive ion) i...,24203-36-9,295O53K152,solid,"{'group': ['approved', 'investigational']}",...,None,None,None,//s3-us-west-2.amazonaws.com/drugbank/fda_labe...,//s3-us-west-2.amazonaws.com/drugbank/msds/DB0...,39.0983,38.963706861,"{'property': [{'kind': 'logP', 'value': '0.2',...",DB01345,-2.609656
13,small molecule,2007-07-06,2024-01-02,"{'@primary': 'true', '#text': 'DB01378'}",Magnesium cation,"Magnesium hydroxide is used primarily in ""Milk...",22537-22-0,T6V3LHY838,solid,"{'group': ['approved', 'nutraceutical']}",...,None,None,None,NaN,//s3-us-west-2.amazonaws.com/drugbank/msds/DB0...,24.305,23.985041898,"{'property': [{'kind': 'logP', 'value': '-0.57...",DB01378,-2.609656
14,small molecule,2007-07-08,2021-02-21,"{'@primary': 'true', '#text': 'DB01396'}",Digitoxin,A cardiac glycoside sometimes used in place of...,71-63-6,E90NZP2L9U,solid,"{'group': ['approved', 'investigational']}",...,"{'enzyme': [{'@position': '1', 'id': 'BE000353...","{'carrier': {'@position': '1', 'id': 'BE000053...","{'transporter': [{'@position': '1', 'id': 'BE0...",NaN,//s3-us-west-2.amazonaws.com/drugbank/msds/DB0...,764.9391,764.434692134,"{'property': [{'kind': 'logP', 'value': '2.33'...",DB01396,-2.609656
15,small molecule,2007-07-24,2023-12-02,"{'@primary': 'true', '#text': 'DB01430'}",Almitrine,Almitrine is a respiratory stimulant that enha...,27469-53-0,9A1222NBG4,solid,{'group': 'approved'},...,None,None,None,NaN,NaN,477.5522,477.245250373,"{'property': [{'kind': 'logP', 'value': '4.9',...",DB01430,-2.609656
16,small molecule,2010-09-15,2020-06-12,"{'@primary': 'true', '#text': 'DB08348'}","N~2~,N~2~-DIMETHYL-N~1~-(6-OXO-5,6-DIHYDROPHEN...",None,None,NA92ZAR7N2,solid,{'group': 'experimental'},...,None,None,None,NaN,NaN,295.3358,295.132076803,"{'property': [{'kind': 'logP', 'value': '1.88'...",DB08348,-2.391322
17,small molecule,2005-06-13,2020-07-02,"[{'@primary': 'true', '#text': 'DB02458'}, EXP...","S-(2,4-dinitrophenyl)glutathione",None,26289-39-4,HL4G8D2C8T,solid,{'group': 'experimental'},...,None,None,None,NaN,NaN,473.415,473.085262543,"{'property': [{'kind': 'logP', 'value': '-1.3'...",DB02458,-2.354361
18,small molecule,2007-10-21,2024-01-02,"{'@primary': 'true', '#text': 'DB04930'}",Permethrin,A pyrethroid insecticide commonly used in the ...,52645-53-1,509F88P9SZ,solid,"{'group': ['approved', 'investigational']}",...,"{'enzyme': {'@position': '1', 'id': 'BE0003549...",None,None,//s3-us-west-2.amazonaws.com/drugbank/fda_labe...,//s3-us-west-2.amazonaws.com/drugbank/msds/DB0...,391.288,390.07894992,"{'property': [{'kind': 'logP', 'value': '6.24'...",DB04930,-2.351940
19,small molecule,2007-07-30,2024-01-02,"{'@primary': 'true', '#text': 'DB01438'}",Phenazopyridine,"Phenazopyridine, also known as Pyridium, is a ...",94-78-0,K2J09EMJ52,solid,{'group': 'approved'},...,None,None,None,NaN,//s3-us-west-2.amazonaws.com/drugbank/msds/DB0...,213.2385,213.101445377,"{'property': [{'kind': 'logP', 'value': '2.31'...",DB01438,-2.351940
20,small molecule,2005-06-13,2021-05-07,"[{'@primary': 'true', '#text': 'DB01121'}, APR...",Phenacemide,Phenacemide is used to control certain seizure...,63-98-9,PAI7J52V09,solid,{'group': 'approved'},...,None,None,None,NaN,//s3-us-west-2.amazonaws.com/drugbank/msds/DB0...,178.1879,178.074227574,"{'property': [{'kind': 'logP', 'value': '0.81'...",DB01121,-2.351940
21,small molecule,2005-06-13,2020-06-12,"[{'@primary': 'true', '#text': 'DB02059'}, EXP...",Adenosine-5-Diphosphoribose,None,None,None,solid,{'group': 'experimental'},...,None,None,None,NaN,NaN,559.3157,559.071673493,"{'property': [{'kind': 'logP', 'value': '-1.8'...",DB02059,-2.334706
22,small molecule,2005-06-13,2024-01-02,"[{'@primary': 'true', '#text': 'DB00484'}, APR...",Brimonidine,Brimonidine is an alpha-adrenergic agonist and...,59803-98-4,E6GNX3HHTE,solid,{'group': 'approved'},...,"{'enzyme': {'@position': '1', 'id': 'BE0003539...",None,None,//s3-us-west-2.amazonaws.com/drugbank/fda_labe...,//s3-us-west-2.amazonaws.com/drugbank/msds/DB0...,292.135,291.011957992,"{'property': [{'kind': 'logP', 'value': '1.27'...",DB00484,-2.322927
23,small molecule,2005-06-13,2024-01-02,"[{'@primary': 'true', '#text': 'DB00575'}, APR...",Clonidine,Clonidine is an imidazole derivate that acts a...,4205-90-7,MN3L5RMN02,solid,{'group': 'approved'},...,"{'enzyme': [{'@position': '1', 'id': 'BE000243...","{'carrier': {'@position': '1', 'id': 'BE000053...","{'transporter': [{'@position': '1', 'id': 'BE0...",NaN,//s3-us-west-2.amazonaws.com/drugbank/msds/DB0...,230.094,229.017352717,"{'property': [{'kind': 'logP', 'value': '2.55'...",DB00575,-2.322927
24,small molecule,2007-09-11,2020-06-12,"{'@primary': 'true', '#text': 'DB04805'}",Virginiamycin S1,"One of the components of virginiamycin, a cycl...",23152-29-6,J91D5GN5AT,solid,{'group': 'experimental'},...,None,None,None,NaN,NaN,823.904,823.354090806,"{'property': [{'kind': 'logP', 'value': '2.25'...",DB04805,-2.316614
25,small molecule,2007-09-11,2020-06-12,"{'@primary': 'true', '#text': 'DB04602'}",PUROMYCIN AMINONUCLEOSIDE-5'-MONOPHOSPHATE,None,None,None,solid,{'group': 'experimental'},...,None,None,None,NaN,NaN,374.2896,374.110368882,"{'property': [{'kind': 'logP', 'value': '-1.4'...",DB04602,-2.316614
26,small molecule,2007-09-11,2020-06-12,"{'@primary': 'true', '#text': 'DB04674'}","2-HYDROXY-3,5-DIIODOBENZOIC ACID",None,None,1496OH15B6,solid,{'group': 'experimental'},...,None,"{'carrier': {'@position': '1', 'id': 'BE000033...",None,NaN,NaN,389.9138,389.824980834,"{'property': [{'kind': 'logP', 'value': '3.13'...",DB04674,-2.175121
27,small molecule,2005-06-13,2024-01-02,"[{'@primary': 'true', '#text': 'DB01110'}, APR...",Miconazole,Miconazole is a broad-spectrum azole antifunga...,22916-47-8,7NNO0D7S5M,solid,"{'group': ['approved', 'investigational', 'vet...",...,"{'enzyme': [{'@position': '1', 'id': 'BE000279...","{'carrier': {'@position': '1', 'id': 'BE000053...","{'transporter': {'@position': '1', 'id': 'BE00...",//s3-us-west-2.amazonaws.com/drugbank/fda_labe...,//s3-us-west-2.amazonaws.com/drugbank/msds/DB0...,416.129,413.986023908,"{'property': [{'kind': 'logP', 'value': '5.86'...",DB01110,-2.165328
28,small molecule,2005-06-13,2023-07-18,"[{'@primary': 'true', '#text': 'DB04216'}, EXP...",Quercetin,Quercetin is a flavonol widely distributed in ...,117-39-5,9IKM0I5T1E,solid,"{'group': ['experimental', 'investigational']}",...,"{'enzyme': [{'@position': '1', 'id': 'BE000288...","{'carrier': {'@position': '1', 'id': 'BE000053...","{'transporter': [{'@position': '1', 'id': 'BE0...",NaN,NaN,302.2357,302.042652674,"{'property': [{'kind': 'logP', 'value': '1.81'...",DB04216,-2.123988
29,small molecule,2005-06-13,2020-06-12,"[{'@primary': 'true', '#text': 'DB03886'}, EXP...",Biopterin,A natural product that has been considered as ...,None,E54CTM794Y,solid,{'group': 'experimental'},...,None,None,None,NaN,NaN,237.2153,237.086189243,"{'property': [{'kind': 'logP', 'value': '-1.1'...",DB03886,-2.074745
30,small molecule,2007-07-06,2020-06-12,"[{'@primary': 'true', '#text': 'DB01370'}, DB1...",Aluminium,A metallic element that has the atomic number ...,7429-90-5,CPD4NFA903,solid,"{'group': ['approved', 'investigational']}",...,None,"{'carrier': {'@position': '1', 'id': 'BE000053...",None,NaN,NaN,26.9815,26.981538441,"{'property': [{'kind': 'logP', 'value': '1.45'...",DB01370,-2.060631
31,small molecule,2005-06-13,2020-08-01,"[{'@primary': 'true', '#text': 'DB02684'}, EXP...",5'-O-(L-Cysteinylsulfamoyl)adenosine,None,None,None,solid,{'group': 'experimental'},...,None,None,None,NaN,NaN,449.463,449.078737377,"{'property': [{'kind': 'logP', 'value': '-1.3'...",DB02684,-2.028148
32,small molecule,2005-06-13,2020-07-02,"[{'@primary': 'true', '#text': 'DB02510'}, EXP...",5'-O-(L-Prolylsulfamoyl)adenosine,None,None,None,solid,{'group': 'experimental'},...,None,None,None,NaN,NaN,443.435,443.122316751,"{'property': [{'kind': 'logP', 'value': '-3.6'...",DB02510,-2.028148
33,small molecule,2005-06-13,2020-06-12,"[{'@primary': 'true', '#text': 'DB03376'}, EXP...",5'-O-(N-(Alanyl)sulfamoyl)adenosine,None,112921-04-7,48GG0U2X78,solid,{'group': 'experimental'},...,None,None,None,NaN,NaN,417.398,417.106666687,"{'property': [{'kind': 'logP', 'value': '-3.9'...",DB03376,-2.028148
34,small molecule,2005-06-13,2023-12-02,"[{'@primary': 'true', '#text': 'DB00561'}, APR...",Doxapram,A central respiratory stimulant with a brief d...,309-29-5,94F3830Q73,solid,"{'group': ['approved', 'vet_approved']}",...,None,None,None,//s3-us-west-2.amazonaws.com/drugbank/fda_labe...,//s3-us-west-2.amazonaws.com/drugbank/msds/DB0...,378.5072,378.230728214,"{'property': [{'kind': 'logP', 'value': '3.65'...",DB00561,-2.002086
35,small molecule,2005-06-13,2020-08-01,"[{'@primary': 'true', '#text': 'DB02733'}, EXP...",Purvalanol,None,None,None,solid,{'group': 'experimental'},...,None,None,None,NaN,NaN,432.904,432.167666403,"{'property': [{'kind': 'logP', 'value': '3.62'...",DB02733,-1.985955
36,small molecule,2005-06-13,2020-06-12,"[{'@primary': 'true', '#text': 'DB03314'}, EXP...",5-fluorotryptophan,5-fluorotryptophan can be used as substrate an...,16626-02-1,17H03VO4KZ,solid,{'group': 'experimental'},...,None,None,None,NaN,//s3-us-west-2.amazonaws.com/drugbank/msds/DB0...,222.2156,222.080455811,"{'property': [{'kind': 'logP', 'value': '-1', ...",DB03314,-1.982137
37,small molecule,2007-09-11,2020-06-12,"{'@primary': 'true', '#text': 'DB04723'}",2-(3-GUANIDINOPHENYL)-3-MERCAPTOPROPANOIC ACID,None,None,None,solid,{'group': 'experimental'},...,None,None,None,NaN,NaN,239.294,239.072847365,"{'property': [{'kind': 'logP', 'value': '0.52'...",DB04723,-1.977283
38,small molecule,2010-09-15,2020-06-12,"{'@primary': 'true', '#text': 'DB06835'}",(2S)-2-[3-(AMINOMETHYL)PHENYL]-3-{(S)-HYDROXY[...,None,None,None,solid,{'group': 'experimental'},...,None,None,None,NaN,NaN,482.53,482.164043936,"{'property': [{'kind': 'logP', 'value': '-0.57...",DB06835,-1.977283
39,small molecule,2010-09-15,2020-06-12,"{'@primary': 'true', '#text': 'DB06921'}",(2S)-2-[3-(AMINOMETHYL)PHENYL]-3-[(R)-HYDROXY{...,None,None,None,solid,{'group': 'experimental'},...,None,None,None,NaN,NaN,454.477,454.132743808,"{'property': [{'kind': 'logP', 'value': '-0.63...",DB06921,-1.977283
40,small molecule,2010-09-15,2020-06-12,"{'@primary': 'true', '#text': 'DB07136'}",BX-528,None,607837-17-2,60045PL22T,solid,{'group': 'experimental'},...,None,None,None,NaN,NaN,496.557,496.179694,"{'property': [{'kind': 'logP', 'value': '-0.43...",DB07136,-1.977283
41,small molecule,2010-09-15,2020-06-12,"{'@primary': 'true', '#text': 'DB07157'}","(5R,6S,8S)-8-[3-(AMINOMETHYL)PHENYL]-6-HYDROXY...",None,None,None,solid,{'group': 'experimental'},...,None,None,None,NaN,NaN,450.422,450.15558774,"{'property': [{'kind': 'logP', 'value': '0.33'...",DB07157,-1.977283
42,small molecule,2010-09-15,2020-06-12,"{'@primary': 'true', '#text': 'DB07182'}",(2S)-2-(3-Carbamimidamidophenyl)-3-[hydroxy(3-...,None,None,None,solid,{'group': 'experimental'},...,None,None,None,NaN,NaN,389.392,389.150443263,"{'property': [{'kind': 'logP', 'value': '1.51'...",DB07182,-1.977283
43,small molecule,2010-09-15,2020-06-12,"{'@primary': 'true', '#text': 'DB07269'}",(2S)-2-[3-(AMINOMETHYL)PHENYL]-3-[(R)-[(1R)-1-...,None,None,None,solid,{'group': 'experimental'},...,None,None,None,NaN,NaN,448.4492,448.176323182,"{'property': [{'kind': 'logP', 'value': '0.01'...",DB07269,-1.977283

In [33]:
IV_4S_db = dict()
with open('IV_to_4S_-1.96_drugs.txt') as f:
    for line in f.readlines():
        line = line.strip()
        id = line.split(',')[0]
        z_score = float(line.split(',')[1])
        IV_4S_db[id] = z_score
        
IV_to_4S = data[data['id'].isin(IV_4S_db)].copy()
# Add the proximity_z column based on the mapping
IV_to_4S['proximity_z'] = IV_to_4S['id'].map(IV_4S_db)
IV_to_4S.sort_values(by='proximity_z', inplace=True)
IV_to_4S.reset_index(drop=True, inplace=True)
IV_to_4S.to_csv("IV_to_4S.csv", na_rep='NULL')
IV_to_4S

,@type,@created,@updated,drugbank-id,name,description,cas-number,unii,state,groups,...,enzymes,carriers,transporters,fda-label,msds,average-mass,monoisotopic-mass,calculated-properties,id,proximity_z
0,small molecule,2005-06-13,2024-01-02,"[{'@primary': 'true', '#text': 'DB00242'}, APR...",Cladribine,An antineoplastic agent used in the treatment ...,4291-63-8,47M74X9YT5,solid,"{'group': ['approved', 'investigational']}",...,"{'enzyme': {'@position': '1', 'id': 'BE0002804...",None,"{'transporter': [{'@position': '1', 'id': 'BE0...",NaN,//s3-us-west-2.amazonaws.com/drugbank/msds/DB0...,285.687,285.062866982,"{'property': [{'kind': 'logP', 'value': '-0.12...",DB00242,-7.383426
1,small molecule,2010-09-15,2020-06-12,"{'@primary': 'true', '#text': 'DB07954'}",3-isobutyl-1-methyl-7H-xanthine,None,28822-58-4,TBT296U68M,solid,{'group': 'experimental'},...,None,None,None,NaN,NaN,222.2438,222.111675712,"{'property': [{'kind': 'logP', 'value': '0.84'...",DB07954,-7.218775
2,small molecule,2010-09-15,2020-06-12,"{'@primary': 'true', '#text': 'DB06843'}","2',5'-DIDEOXY-ADENOSINE 3'-MONOPHOSPHATE",None,None,None,solid,{'group': 'experimental'},...,None,None,None,NaN,NaN,315.2224,315.073255095,"{'property': [{'kind': 'logP', 'value': '-1.8'...",DB06843,-6.052646
3,small molecule,2005-06-13,2022-06-27,"[{'@primary': 'true', '#text': 'DB02587'}, EXP...",Colforsin,Potent activator of the adenylate cyclase syst...,66575-29-9,1F7A44V6OU,solid,"{'group': ['experimental', 'investigational']}",...,None,None,"{'transporter': {'@position': '1', 'id': 'BE00...",NaN,NaN,410.5012,410.230453442,"{'property': [{'kind': 'logP', 'value': '1.28'...",DB02587,-6.052646
4,small molecule,2005-06-13,2024-01-02,"[{'@primary': 'true', '#text': 'DB00920'}, APR...",Ketotifen,Ketotifen is a benzocycloheptathiophene deriva...,34580-13-7,X49220T18G,solid,{'group': 'approved'},...,"{'enzyme': [{'@position': '1', 'id': 'BE000367...",None,None,//s3-us-west-2.amazonaws.com/drugbank/fda_labe...,NaN,309.425,309.118734925,"{'property': [{'kind': 'logP', 'value': '3.49'...",DB00920,-6.044917
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
316,small molecule,2005-06-13,2020-06-12,"[{'@primary': 'true', '#text': 'DB03860'}, EXP...",ICI-164384,None,98007-99-9,84LT43726C,solid,{'group': 'experimental'},...,None,None,None,NaN,NaN,525.8054,525.418194631,"{'property': [{'kind': 'logP', 'value': '7.88'...",DB03860,-1.967870
317,small molecule,2010-09-15,2020-06-12,"{'@primary': 'true', '#text': 'DB07757'}","(9aS)-4-bromo-9a-butyl-7-hydroxy-1,2,9,9a-tetr...",None,None,None,solid,{'group': 'experimental'},...,None,None,None,NaN,NaN,335.236,334.056842499,"{'property': [{'kind': 'logP', 'value': '5.1',...",DB07757,-1.967870
318,small molecule,2010-09-15,2020-06-12,"{'@primary': 'true', '#text': 'DB07032'}",2-(4-HYDROXY-PHENYL)BENZOFURAN-5-OL,None,None,None,solid,{'group': 'experimental'},...,None,None,None,NaN,NaN,226.2274,226.062994186,"{'property': [{'kind': 'logP', 'value': '3.19'...",DB07032,-1.967870
319,small molecule,2005-06-13,2020-06-12,"[{'@primary': 'true', '#text': 'DB03882'}, EXP...","5-Alpha-Androstane-3-Beta,17beta-Diol",None,571-20-0,6J0K4253QD,solid,{'group': 'experimental'},...,None,"{'carrier': {'@position': '1', 'id': 'BE000068...",None,NaN,NaN,292.4562,292.240230268,"{'property': [{'kind': 'logP', 'value': '3.56'...",DB03882,-1.967870
320,small molecule,2010-09-15,2020-06-12,"{'@primary': 'true', '#text': 'DB06937'}","4-(6-HYDROXY-BENZO[D]ISOXAZOL-3-YL)BENZENE-1,3...",None,None,None,solid,{'group': 'experimental'},...,None,None,None,NaN,NaN,243.2149,243.053157781,"{'property': [{'kind': 'logP', 'value': '2.18'...",DB06937,-1.967870

In [34]:
III_I_db = dict()
with open('III_to_I_-1.96_drugs.txt') as f:
    for line in f.readlines():
        line = line.strip()
        id = line.split(',')[0]
        z_score = float(line.split(',')[1])
        III_I_db[id] = z_score
        
III_to_I = data[data['id'].isin(III_I_db)].copy()
# Add the proximity_z column based on the mapping
III_to_I['proximity_z'] = III_to_I['id'].map(III_I_db)
III_to_I.sort_values(by='proximity_z', inplace=True)
III_to_I.reset_index(drop=True, inplace=True)
III_to_I.to_csv("III_to_I.csv", na_rep='NULL')
III_to_I

,@type,@created,@updated,drugbank-id,name,description,cas-number,unii,state,groups,...,enzymes,carriers,transporters,fda-label,msds,average-mass,monoisotopic-mass,calculated-properties,id,proximity_z
0,small molecule,2005-06-13,2024-01-02,"[{'@primary': 'true', '#text': 'DB00484'}, APR...",Brimonidine,Brimonidine is an alpha-adrenergic agonist and...,59803-98-4,E6GNX3HHTE,solid,{'group': 'approved'},...,"{'enzyme': {'@position': '1', 'id': 'BE0003539...",None,None,//s3-us-west-2.amazonaws.com/drugbank/fda_labe...,//s3-us-west-2.amazonaws.com/drugbank/msds/DB0...,292.135,291.011957992,"{'property': [{'kind': 'logP', 'value': '1.27'...",DB00484,-3.165738
1,small molecule,2005-06-13,2024-01-02,"[{'@primary': 'true', '#text': 'DB00575'}, APR...",Clonidine,Clonidine is an imidazole derivate that acts a...,4205-90-7,MN3L5RMN02,solid,{'group': 'approved'},...,"{'enzyme': [{'@position': '1', 'id': 'BE000243...","{'carrier': {'@position': '1', 'id': 'BE000053...","{'transporter': [{'@position': '1', 'id': 'BE0...",NaN,//s3-us-west-2.amazonaws.com/drugbank/msds/DB0...,230.094,229.017352717,"{'property': [{'kind': 'logP', 'value': '2.55'...",DB00575,-3.165738
2,small molecule,2005-06-13,2020-06-12,"[{'@primary': 'true', '#text': 'DB03886'}, EXP...",Biopterin,A natural product that has been considered as ...,None,E54CTM794Y,solid,{'group': 'experimental'},...,None,None,None,NaN,NaN,237.2153,237.086189243,"{'property': [{'kind': 'logP', 'value': '-1.1'...",DB03886,-3.020034
3,small molecule,2005-06-13,2023-12-02,"[{'@primary': 'true', '#text': 'DB00800'}, APR...",Fenoldopam,A dopamine D1 receptor agonist that is used as...,67227-56-9,INU8H2KAWG,solid,{'group': 'approved'},...,None,None,None,//s3-us-west-2.amazonaws.com/drugbank/fda_labe...,NaN,305.756,305.08187109,"{'property': [{'kind': 'logP', 'value': '2.39'...",DB00800,-3.016623
4,small molecule,2005-06-13,2023-12-02,"[{'@primary': 'true', '#text': 'DB00561'}, APR...",Doxapram,A central respiratory stimulant with a brief d...,309-29-5,94F3830Q73,solid,"{'group': ['approved', 'vet_approved']}",...,None,None,None,//s3-us-west-2.amazonaws.com/drugbank/fda_labe...,//s3-us-west-2.amazonaws.com/drugbank/msds/DB0...,378.5072,378.230728214,"{'property': [{'kind': 'logP', 'value': '3.65'...",DB00561,-2.983358
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
164,small molecule,2005-06-13,2020-06-12,"[{'@primary': 'true', '#text': 'DB02109'}, EXP...",Hadacidin,None,689-13-4,BFO5P1010A,solid,{'group': 'experimental'},...,None,None,None,NaN,NaN,119.0761,119.021857653,"{'property': [{'kind': 'logP', 'value': '-0.97...",DB02109,-1.974911
165,small molecule,2007-09-11,2020-06-12,"{'@primary': 'true', '#text': 'DB04770'}","O6-(R)-ROSCOVITINE, R-2-(6-BENZYLOXY-9-ISOPROP...",None,None,None,solid,{'group': 'experimental'},...,None,None,None,NaN,NaN,355.4341,355.200825069,"{'property': [{'kind': 'logP', 'value': '3.23'...",DB04770,-1.966075
166,small molecule,2007-09-11,2020-06-12,"{'@primary': 'true', '#text': 'DB04776'}",(2R)-2-({6-[benzyl(methyl)amino]-9-isopropyl-9...,None,None,None,solid,{'group': 'experimental'},...,None,None,None,NaN,NaN,368.4759,368.232459548,"{'property': [{'kind': 'logP', 'value': '3.45'...",DB04776,-1.966075
167,small molecule,2005-06-13,2024-01-02,"[{'@primary': 'true', '#text': 'DB00165'}, NUT...",Pyridoxine,Pyridoxine is the 4-methanol form of vitamin B...,65-23-6,KV2JZ1BI6Z,solid,"{'group': ['approved', 'investigational', 'nut...",...,"{'enzyme': [{'@position': '1', 'id': 'BE000354...","{'carrier': {'@position': '1', 'id': 'BE000053...","{'transporter': {'@position': '1', 'id': 'BE00...",//s3-us-west-2.amazonaws.com/drugbank/fda_labe...,//s3-us-west-2.amazonaws.com/drugbank/msds/DB0...,169.1778,169.073893223,"{'property': [{'kind': 'logP', 'value': '-0.57...",DB00165,-1.966075
168,small molecule,2005-06-13,2024-01-02,"[{'@primary': 'true', '#text': 'DB00147'}, NUT...",Pyridoxal,The 4-carboxyaldehyde form of vitamin B 6 whic...,66-72-8,3THM379K8A,solid,"{'group': ['experimental', 'nutraceutical']}",...,None,None,None,NaN,//s3-us-west-2.amazonaws.com/drugbank/msds/DB0...,167.162,167.058243159,"{'property': [{'kind': 'logP', 'value': '0.02'...",DB00147,-1.966075

In [35]:
IV_I_db = dict()
with open('IV_to_I_-1.96_drugs.txt') as f:
    for line in f.readlines():
        line = line.strip()
        id = line.split(',')[0]
        z_score = float(line.split(',')[1])
        IV_I_db[id] = z_score
        
IV_to_I = data[data['id'].isin(IV_I_db)].copy()
# Add the proximity_z column based on the mapping
IV_to_I['proximity_z'] = IV_to_I['id'].map(IV_I_db)
IV_to_I.sort_values(by='proximity_z', inplace=True)
IV_to_I.reset_index(drop=True, inplace=True)
IV_to_I.to_csv("IV_to_I.csv", na_rep='NULL')
IV_to_I

,@type,@created,@updated,drugbank-id,name,description,cas-number,unii,state,groups,...,enzymes,carriers,transporters,fda-label,msds,average-mass,monoisotopic-mass,calculated-properties,id,proximity_z
0,small molecule,2005-06-13,2020-06-12,"[{'@primary': 'true', '#text': 'DB01742'}, EXP...",(3r)-1-Acetyl-3-Methylpiperidine,None,None,None,solid,{'group': 'experimental'},...,None,None,None,NaN,NaN,141.2108,141.115364107,"{'property': [{'kind': 'logP', 'value': '0.91'...",DB01742,-4.019090
1,small molecule,2005-06-13,2020-07-02,"[{'@primary': 'true', '#text': 'DB02419'}, EXP...",Ethyl Oxo(Piperidin-1-Yl)Acetate,None,53074-96-7,D7IIF4X1TU,solid,{'group': 'experimental'},...,None,None,None,NaN,NaN,185.2203,185.105193351,"{'property': [{'kind': 'logP', 'value': '1.01'...",DB02419,-4.019090
2,small molecule,2005-06-13,2020-06-12,"[{'@primary': 'true', '#text': 'DB03393'}, EXP...",Sanglifehrin A,None,None,None,solid,{'group': 'experimental'},...,None,None,None,NaN,NaN,1090.3902,1089.661338023,"{'property': [{'kind': 'logP', 'value': '4.52'...",DB03393,-4.019090
3,small molecule,2005-06-13,2020-06-12,"[{'@primary': 'true', '#text': 'DB01873'}, EXP...",Epothilone D,None,189453-10-9,T0358E0YUF,solid,{'group': 'investigational'},...,"{'enzyme': {'@position': '1', 'id': 'BE0002638...",None,None,NaN,NaN,491.683,491.270544117,"{'property': [{'kind': 'logP', 'value': '4.54'...",DB01873,-3.904165
4,small molecule,2005-06-13,2023-01-14,"[{'@primary': 'true', '#text': 'DB03010'}, EXP...",Patupilone,Epothilone B is a 16-membered macrolide that m...,152044-54-7,UEC0H0URSE,solid,"{'group': ['experimental', 'investigational']}",...,"{'enzyme': {'@position': '1', 'id': 'BE0002638...",None,None,NaN,NaN,507.683,507.265458739,"{'property': [{'kind': 'logP', 'value': '3.7',...",DB03010,-3.904165
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
356,small molecule,2005-06-13,2020-06-12,"[{'@primary': 'true', '#text': 'DB04194'}, EXP...",Triacetylchitotriose,None,13319-32-9,None,solid,{'group': 'experimental'},...,None,None,None,NaN,NaN,627.5928,627.248682279,"{'property': [{'kind': 'logP', 'value': '-2.5'...",DB04194,-1.985010
357,small molecule,2005-06-13,2020-06-12,"[{'@primary': 'true', '#text': 'DB03487'}, EXP...",(S)-Aspartimide,None,73537-92-5,None,solid,{'group': 'experimental'},...,None,None,None,NaN,NaN,114.1026,114.042927446,"{'property': [{'kind': 'logP', 'value': '-1.8'...",DB03487,-1.985010
358,small molecule,2005-06-13,2020-06-12,"[{'@primary': 'true', '#text': 'DB03967'}, EXP...",Dodecyl sulfate,None,151-41-7,DIQ16UC154,solid,{'group': 'experimental'},...,None,None,None,NaN,NaN,266.397,266.15518001,"{'property': [{'kind': 'logP', 'value': '1.77'...",DB03967,-1.985010
359,small molecule,2005-06-13,2023-07-18,"[{'@primary': 'true', '#text': 'DB03006'}, EXP...",Arsanilic acid,An arsenical which has been used as a feed add...,98-50-0,UDX9AKS7GM,solid,"{'group': ['experimental', 'vet_approved']}",...,None,None,None,NaN,NaN,217.0542,216.972014544,"{'property': [{'kind': 'logP', 'value': '-0.42...",DB03006,-1.985010
360,small molecule,2005-06-13,2020-06-12,"[{'@primary': 'true', '#text': 'DB02116'}, EXP...",Olomoucine,None,101622-51-9,6A839B2HYS,solid,{'group': 'experimental'},...,None,None,None,NaN,NaN,298.343,298.154209228,"{'property': [{'kind': 'logP', 'value': '1.58'...",DB02116,-1.978166

In [36]:
# IV_I_list.fillna('Not available', inplace = True)

In [37]:
IV_III_db = dict()
with open('IV_to_III_-1.96_drugs.txt') as f:
    for line in f.readlines():
        line = line.strip()
        id = line.split(',')[0]
        z_score = float(line.split(',')[1])
        IV_III_db[id] = z_score
        
IV_to_III = data[data['id'].isin(IV_III_db)].copy()
# Add the proximity_z column based on the mapping
IV_to_III['proximity_z'] = IV_to_III['id'].map(IV_III_db)
IV_to_III.sort_values(by='proximity_z', inplace=True)
IV_to_III.reset_index(drop=True, inplace=True)
IV_to_III.to_csv("IV_to_III.csv", na_rep='NULL')
IV_to_III

,@type,@created,@updated,drugbank-id,name,description,cas-number,unii,state,groups,...,enzymes,carriers,transporters,fda-label,msds,average-mass,monoisotopic-mass,calculated-properties,id,proximity_z
0,biotech,2005-06-13,2024-01-02,"[{'@primary': 'true', '#text': 'DB00013'}, BTD...",Urokinase,Urokinase is an endogenous peptide that is cle...,9039-53-6,83G67E21XI,liquid,"{'group': ['approved', 'investigational', 'wit...",...,"{'enzyme': {'@position': '1', 'id': 'BE0001198...",None,None,NaN,NaN,NaN,NaN,NaN,DB00013,-6.598139
1,small molecule,2005-06-13,2023-12-02,"[{'@primary': 'true', '#text': 'DB00786'}, APR...",Marimastat,"Used in the treatment of cancer, Marmiastat is...",154039-60-8,D5EQV23TDS,solid,{'group': 'investigational'},...,None,None,None,NaN,NaN,331.4079,331.210721053,"{'property': [{'kind': 'logP', 'value': '0.41'...",DB00786,-6.037934
2,small molecule,2005-06-13,2021-02-21,"[{'@primary': 'true', '#text': 'DB03880'}, EXP...",Batimastat,None,130370-60-4,BK349F52C9,solid,{'group': 'experimental'},...,None,None,None,NaN,NaN,477.64,477.175597875,"{'property': [{'kind': 'logP', 'value': '3.23'...",DB03880,-4.788114
3,biotech,2005-06-13,2024-01-02,"[{'@primary': 'true', '#text': 'DB00009'}, BTD...",Alteplase,Alteplase is a recombinant tissue plasminogen ...,105857-23-6,1RXS4UE564,liquid,"{'group': ['approved', 'investigational']}",...,None,None,None,NaN,NaN,NaN,NaN,NaN,DB00009,-4.467055
4,biotech,2005-06-13,2024-01-02,"[{'@primary': 'true', '#text': 'DB00015'}, BTD...",Reteplase,"Human tissue plasminogen activator, purified, ...",133652-38-7,DQA630RIE9,liquid,"{'group': ['approved', 'investigational']}",...,None,None,None,NaN,NaN,NaN,NaN,NaN,DB00015,-4.467055
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199,biotech,2009-02-12,2024-01-02,"{'@primary': 'true', '#text': 'DB06692'}",Aprotinin,Aprotinin is a protein-based drug that is also...,9087-70-1,04XPW8C0FL,liquid,"{'group': ['approved', 'investigational', 'wit...",...,"{'enzyme': {'@position': '1', 'id': 'BE0002180...",None,None,//s3-us-west-2.amazonaws.com/drugbank/fda_labe...,//s3-us-west-2.amazonaws.com/drugbank/msds/DB0...,NaN,NaN,NaN,DB06692,-1.998991
200,small molecule,2005-06-13,2024-01-02,"[{'@primary': 'true', '#text': 'DB00252'}, APR...",Phenytoin,Phenytoin is classified as a hydantoin derivat...,57-41-0,6158TKW0C5,solid,"{'group': ['approved', 'vet_approved']}",...,"{'enzyme': [{'@position': '1', 'id': 'BE000279...","{'carrier': [{'@position': '1', 'id': 'BE00005...","{'transporter': [{'@position': '1', 'id': 'BE0...",NaN,//s3-us-west-2.amazonaws.com/drugbank/msds/DB0...,252.268,252.089877638,"{'property': [{'kind': 'logP', 'value': '2.26'...",DB00252,-1.993636
201,small molecule,2005-06-13,2020-06-12,"[{'@primary': 'true', '#text': 'DB03023'}, EXP...",1-Tert-Butyl-3-(4-Chloro-Phenyl)-1h-Pyrazolo[3...,None,None,None,solid,{'group': 'experimental'},...,None,None,None,NaN,NaN,302.782,302.117248276,"{'property': [{'kind': 'logP', 'value': '0.49'...",DB03023,-1.987105
202,biotech,2005-06-13,2024-01-02,"[{'@primary': 'true', '#text': 'DB00025'}, BTD...","Antihemophilic factor, human recombinant",Human recombinant antihemophilic factor (AHF) ...,139076-62-3,P89DR4NY54,solid,"{'group': ['approved', 'investigational']}",...,"{'enzyme': [{'@position': '1', 'id': 'BE000004...",None,None,NaN,NaN,NaN,NaN,NaN,DB00025,-1.973235
203,small molecule,2008-08-24,2024-01-02,"{'@primary': 'true', '#text': 'DB06689'}",Ethanolamine oleate,Ethanolamine oleate is a mild sclerosing agent...,2272-11-9,U4RY8MRX7C,solid,{'group': 'approved'},...,None,None,None,NaN,NaN,343.5444,343.308644183,"{'property': [{'kind': 'logP', 'value': '7.68'...",DB06689,-1.967356