In [1]:
import pandas as pd

In [4]:
IntOGen_drivers = pd.read_csv('/hdd/edward/the-project/data/Cell/IntOGen-DriverGenes_NBL.tsv', sep='\t')
IntOGen_drivers

     Symbol  Mutations  Samples  Samples (%)  Cohorts
0       ALK         37       36         6.41        5
1      ATRX         14       13         2.31        3
2      FBN2          8        7         1.25        1
3    PTPN11          8        7         1.25        1
4       NF1         12        5         0.89        2
5    PRUNE2         13        5         0.89        1
6     LRP1B          5        5         0.89        1
7    BCORL1          6        5         0.89        2
8      TP63          5        4         0.71        1
9     FBLN2          5        4         0.71        1
10     USP6          6        4         0.71        1
11     MYH9          3        3         0.53        1
12     FLT4          7        3         0.53        1
13    ERBB3          6        3         0.53        1
14     MSI2          3        3         0.53        1
15    KMT2D          5        3         0.53        1
16    PRDM2          4        3         0.53        1
17      TNC          7        3         0.53        1
18    DOT1L          5        3         0.53        1
19    NCOR1          2        2         0.36        1
20     TP53          6        2         0.36        1
21     MYCN          4        2         0.36        1
22   RANBP2          3        2         0.36        1
23     ETV4          3        2         0.36        1
24    MED12          3        2         0.36        1
25    MYO5A          4        2         0.36        1
26     CHD4          3        2         0.36        1
27  SMARCB1          2        2         0.36        1

In [11]:
IntOGen_drivers = set(IntOGen_drivers["Symbol"])
print(len(IntOGen_drivers))
IntOGen_drivers

28

{'ALK',
 'ATRX',
 'BCORL1',
 'CHD4',
 'DOT1L',
 'ERBB3',
 'ETV4',
 'FBLN2',
 'FBN2',
 'FLT4',
 'KMT2D',
 'LRP1B',
 'MED12',
 'MSI2',
 'MYCN',
 'MYH9',
 'MYO5A',
 'NCOR1',
 'NF1',
 'PRDM2',
 'PRUNE2',
 'PTPN11',
 'RANBP2',
 'SMARCB1',
 'TNC',
 'TP53',
 'TP63',
 'USP6'}

In [5]:
oncokb_drivers = pd.read_csv('/hdd/edward/the-project/data/Cell/oncokb_biomarker_drug_associations.tsv', sep='\t')
oncokb_drivers

,Level,Gene,Alterations,Cancer Types,Drugs (for therapeutic implications only)
0,1,BRAF,V600E,All Solid Tumors (excluding Colorectal Cancer),Dabrafenib + Trametinib
1,1,NTRK1,Fusions,All Solid Tumors,Entrectinib
2,1,NTRK1,Fusions,All Solid Tumors,Larotrectinib
3,1,NTRK1,Fusions,All Solid Tumors,Repotrectinib
4,1,NTRK2,Fusions,All Solid Tumors,Entrectinib
...,...,...,...,...,...
70,4,PIK3CA,Oncogenic Mutations,All Solid Tumors,RLY-2608
71,4,PPP2R1A,Oncogenic Mutations,All Solid Tumors,Lunresertib + Camonsertib
72,4,PTEN,Oncogenic Mutations,All Solid Tumors,AZD8186
73,4,PTEN,Oncogenic Mutations,All Solid Tumors,GSK2636771
74,R2,NTRK1,G595R,All Solid Tumors,Entrectinib

In [12]:
oncokb_drivers = set(oncokb_drivers["Gene"])
print(len(oncokb_drivers))
oncokb_drivers

27

{'ALK',
 'ARID1A',
 'BRAF',
 'CCNE1',
 'CDK12',
 'CDKN2A',
 'ERBB2',
 'FBXW7',
 'FGFR1',
 'FGFR2',
 'FGFR3',
 'KRAS',
 'MDM2',
 'MET',
 'MTAP',
 'MTOR',
 'NF1',
 'NRG1',
 'NTRK1',
 'NTRK2',
 'NTRK3',
 'Other Biomarkers',
 'PIK3CA',
 'PPP2R1A',
 'PTEN',
 'RET',
 'TP53'}

In [13]:
oncokb_drivers.remove('Other Biomarkers')
oncokb_drivers

{'ALK',
 'ARID1A',
 'BRAF',
 'CCNE1',
 'CDK12',
 'CDKN2A',
 'ERBB2',
 'FBXW7',
 'FGFR1',
 'FGFR2',
 'FGFR3',
 'KRAS',
 'MDM2',
 'MET',
 'MTAP',
 'MTOR',
 'NF1',
 'NRG1',
 'NTRK1',
 'NTRK2',
 'NTRK3',
 'PIK3CA',
 'PPP2R1A',
 'PTEN',
 'RET',
 'TP53'}

In [14]:
IntOGen_drivers & oncokb_drivers

{'ALK', 'NF1', 'TP53'}

In [16]:
len(IntOGen_drivers | oncokb_drivers)

51

In [17]:
# Example set
curated_set = IntOGen_drivers | oncokb_drivers

# Save to a text file
with open("./Cell/curated_set.txt", "w") as f:
    for gene in curated_set:
        f.write(f"{gene}\n")